name: Release version
on:
  push:
   tags:
    - '*'
    
jobs:
  merge-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Merge development -> main
        uses: devmasx/merge-branch@main
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ github.token }}
