name: Release version
on:
  push:
   tags:
    - '*'
    
jobs:
  merge-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Merge development -> main
        run: |
          git merge  ${{ github.event.release.target_commitish }} -m echo "Release " ${{github.event.release.tag_name }}
          git push
