name: Release version
on:
  push:
   tags:
    - '*'
    
jobs:
  merge-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ github.token }}
