name: Release version
on:
  release:
    types: [released, edited]

jobs:
  merge-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.release.target_commitish}}

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      
      - name: Merge development -> main / master
        run: |
          git fetch --unshallow
          if git show-ref --verify main; then
              git checkout main
          elif git show-ref --verify master; then
              git checkout master
          else
            echo "No master or main branch"
            exit 1
          fi
          git merge  --no-ff ${{github.event.release.target_commitish}} -m "Release ${{github.event.release.tag_name}}"
          git push
