name: Check conflicts
on:
  release:
    types: [prereleased]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.release.target_commitish}}

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      
      - name: Check conflicts
        run: |
          git fetch origin
          git checkout master || git checkout main
          git merge develop --no-ff --no-commit


