name: Check conflicts
on:
  release:
    types: [released]

jobs:
  merge-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.release.target_commitish}}

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      
      - name: Merge development -> main / master
        run:
          git diff --name-only --diff-filter=U

